services:
  app:
    image: kou029w/nttr
    build: "."
    ports: ["8080:8080"]
    depends_on: [redis]
    environment:
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      REDIS_PASSWORD: ""
  redis:
    image: redis:alpine
